apiVersion: apps/v1
kind: Deployment
metadata:
  name: thewatcherpage-uat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thewatcherpage-uat
  template:
    metadata:
      labels:
        app: thewatcherpage-uat
    spec:
      containers:
      - name: thewatcherpageuat
        image: nitron181/the_watcher_repo:v2
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: uat-service
  namespace: gitrunner
spec:
  selector:
    app: thewatcherpage-uat
  ports:
  - name: http
    port: 82
    targetPort: 8002
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uat-ingress
  namespace: gitrunner
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: uat.thewatcherpage.info
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: uat-service
            port:
              name: http
              number: 82