# Generated by Django 4.1.5 on 2023-01-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Website',
        ),
    ]
