# Generated by Django 4.1.5 on 2023-01-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('last_status', models.IntegerField(default=200)),
                ('last_checked', models.DateTimeField()),
                ('last_alert', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
