# Generated by Django 4.1.5 on 2023-01-26 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Website',
            new_name='Dashboard',
        ),
    ]
