# Generated by Django 4.1.5 on 2023-01-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_last_alert_dashboard_last_alert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='Status',
            field=models.IntegerField(default=200),
        ),
    ]
