# Generated by Django 4.1.5 on 2023-01-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_dashboard_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='Last_Alert',
            new_name='last_alert',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='Status_Send_To',
            new_name='status_send_to',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='URL',
            new_name='url',
        ),
    ]
